### ISSUE TITLE
will plugin need apache and nginx rewrite rules?

### ISSUE THREAD

**Issue by bnomei** [johannschopplich/kirby-hashed-assets#1]
.htaccess – put this directly after the RewriteBase statement
```
# RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.+)\.([0-9a-z]{8})\.(js|css)$ $1.$3 [L]
```

Nginx virtual host setup
```
location ~ (.+)\.(?:\w+)\.(js|css)$ {
    try_files $uri $1.$2;
}
```

**Comment by johannschopplich** [comment]
You don't need any additional rewrite rules. That's the beauty!

The manifest file, respectively globbing, will take care of that.

**Comment by bnomei** [comment]
ah  found it.
https://github.com/johannschopplich/kirby-hashed-assets/blob/7587e7a32a802bf33f6da6af51afcd48457a9baa/classes/KirbyExtended/AssetUrls.php#L100

you might mention in your readme that this step is NOT needed. just to make it super clear. like you said thats one of the better parts of your plugin.

**Comment by johannschopplich** [comment]
Good idea! Thanks for the input.
