### ISSUE TITLE
@template not working for virtual subpages

### ISSUE THREAD

**Issue by apps4research** [johannschopplich/kirby-hashed-assets#2]
First let me say, thanks for this great plugin :) It's working like a charm and I am especially happy that it considers the css files in the template folder. However, here I have come across a small problem. 

I have a gallery included in my site - the url is something like https://mydomain.com/gallery/animals
For the gallery I have no specific css in the templates folder. In this case, the plugin returns https://mydomain.com/@template as the url for the css ... it seems to be expecting to find "album.css" and "animals.css" in the template folder, but I have neither as I don't need them. Im using Kirby 3.9.

Any ideas?

**Comment by apps4research** [comment]
The only way I have been able to help myself (apart from creating empty css files) is by including this in the header

```php
<?= css([
    'assets/css/fonts.css',
    'assets/css/index.css',
]) ?>

<?php if (!str_starts_with($page->id(),"gallery")): ?>
<?= css([
    '@template'
]) ?>
```

**Comment by johannschopplich** [comment]
Hi there! Thanks for the flowers.

Have you tried following the [usage guide in the README](https://github.com/johannschopplich/kirby-hashed-assets#usage)? The issue you encounter should already be handled by the guide:

> ⚠️ If no template file exists, `https://example.com/@template` will be echoed. This will lead to HTTP errors and blocked content since the requested file doesn't exist and the error page's HTML will be returned.
> 
> If you are unsure if a template file exists, use the following helpers:
> 
> - `cssTpl()`
> - `jsTpl()`
>
> They will echo a link tag, respectively script tag, only if a template file for current page's template is present.

Please try the helper method instead. 🙂

**Comment by apps4research** [comment]
Ahh, okay thanks Johann, I overlooked that - thanks very much for your quick help ... problem solved :)

**Comment by apps4research** [comment]
Ps: cssTpl returns 

`<link @template href="http://dev.local/assets/css/templates/home.20230928.css" rel="stylesheet">`

Is it normal that @template is rendered in the link?

**Comment by johannschopplich** [comment]
I'm unsure where the `@template` should come from, but you seem to have solved it!

**Comment by apps4research** [comment]
Yeah, me neither, maybe some remnant of my testing ... its working perfect now :)
