### ISSUE TITLE
hashup script running, but files not being hashed

### ISSUE THREAD

**Issue by bigskillet** [johannschopplich/kirby-hashed-assets#3]
I'm running the following script in package.json:

`"build": "webpack --mode=production --progress && hashup"`

...but the files are not being hashed and the console is returning `0 asset files hashed`:

<img width="341" alt="Screenshot 2024-01-22 at 2 31 50 PM" src="https://github.com/johannschopplich/kirby-hashed-assets/assets/682013/b896b616-d05b-4aa0-8346-10acb67a15df">

Here's a link to a test repo: https://github.com/bigskillet/kirby-hashup

**Comment by johannschopplich** [comment]
Hashup expects your JS and CSS assets in their dedicated folder – `assets/js/*.js` and `assets/css/*.css`. The reasoning behind this is to be close to the Kirby default convention for the `css()` and `js()` Kirby helpers.

Please update your build pipeline and move the files into the dedicated folders.

**Comment by bigskillet** [comment]
Ah, thanks for the clarification!

**Comment by bigskillet** [comment]
Ah, thanks for the clarification!

**Comment by johannschopplich** [comment]
Sure thing! I should update the README...
